server:
  port: 8013
  
spring:
  application:
    name: provider
 
#安全中心设置  
security: 
    user: 
        name: root
        password: root   
 
#注册中心指向    
eureka:
  instance:
    appname: ${spring.application.name}                    #注册服务名（默认：也是该值）
    instance-id: ${spring.application.name}:${server.port} #同一服务名称下，必须不一致（默认：ip+名称+端口）
  client: 
    service-url: 
      defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:8888/eureka/